title: "Bawi Sang | Data Analytics Portfolio"
description: "Turning data into insights with Python, SQL, Tableau, Power BI."
theme: minima
url: "https://bawis-lab.github.io"

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md
